# Generated by Django 3.1 on 2020-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactchat', '0002_auto_20200821_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
