# Generated by Django 3.1 on 2020-08-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impactchat', '0004_auto_20200821_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'permissions': [('read_channel', 'Can see the channel and read from it in the view'), ('write_channel', 'Can write in the channel in the view')]},
        ),
    ]
