# Generated by Django 3.1 on 2020-08-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impactchat', '0005_auto_20200821_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'permissions': [('manage_channels', 'Can add a channel using the view')]},
        ),
    ]
