# Generated by Django 3.1 on 2020-08-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactchat', '0006_auto_20200821_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
