# Generated by Django 3.1 on 2020-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactchat', '0007_channel_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
