# Generated by Django 3.1 on 2020-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactadmin', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
