# Generated by Django 3.1 on 2020-08-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impactadmin', '0002_auto_20200830_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
