# Generated by Django 3.1 on 2020-10-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impactadmin', '0003_auto_20200830_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
